### ISSUE TITLE
Plugin is blocking Firefox's new multiprocess support

### ISSUE THREAD

**Issue by danielquinn** [warren-bank/moz-json-data-view#14]
Firefox 54 supports window multiprocessing and the speed improvement is substantial.  However, plugins like this one that only support the legacy format (ie not webextensions) block this feature.

Given that Firefox 57 is slated to drop all support for legacy formats, this is probably something worth looking into.

**Comment by warren-bank** [comment]
Right you are.. Firefox 57 is removing support for the entire addon API (in all of its many incarnations) and from that point forward only allow the execution of WebExtension addons.

That being the case, this addon as well as just about 99.9% of those that were available (on the official "AMO" website) will become unusable in main Mozilla. Some people plan to jump ship and use a fork of Firefox (ex: Palemoon) to continue to run their favorite "legacy" addons.

As for myself, I don't really care. None of my addons saw much usage. The ones that were most interesting simply cannot be rewritten as WebExtension because the API is so limited. Others, such as this one, probably could be rewritten.. but I have no motivation to do so. Users can simply choose to uninstall them if they don't play nicely with major releases of Firefox between now and v57. At which time, it becomes a moot point.

I'm no longer a fan of Mozilla or Firefox, and am currently a perfectly content user of Chromium.

Sorry for any inconvenience.

**Comment by warren-bank** [comment]
fun [article](https://www.ghacks.net/2017/04/27/if-firefox-57-would-be-released-today-2274-add-ons-would-be-compatible/)..

at the time (April 28, 2017), of the 18,814 addons on AMO, only 2,273 claim compatibility with FF v57. So.. maybe my math was off, not 99.9%.. closer to (1 - 2273/18814 =) 87.9%.. that will silently disappear.

**Comment by warren-bank** [comment]
not to change topic, but totally changing topic..

what architecture did you have in mind for [vlattice](https://github.com/danielquinn/vlattice)?

fwiw, I'd absolutely consider a P2P strategy using IPFS for storage. It lends itself perfectly to the viral nature of videos.. having a relatively short-lived popularity spike.

**Comment by danielquinn** [comment]
Actually, I'd never heard of IPFS, so thank you for pointing me in that direction.  Originally I'd envisioned a simple Django stack that handles user auth & preferences via a DHT, hosting the static files on S3 or something with similarly cheap bandwidth.

IPFS is fascinating, but I'd be concerned about disproportionately increasing the costs of new entrants.  Youtubers vary in size & scale, and I'd like to keep the cost of entry low for smaller youtubers.  If using IPFS would mean distributing the storage & streaming costs across the network equally, that would hurt this goal.  There's also the reality of storage costs.  Putting 30gb of video is cheap on S3, while storing it on an EC2 instance (to be friendlier to IPFS) is much more expensive.  It would work nicely for users who just have their own VPS in a cloud somewhere, but I'd worry about the costs for new joiners who just want to post video.

Regardless, IPFS is fascinating and powerful.  Thank you for introducing me to it.  It's good to know what tools I have in my toolbox and I'm already re-thinking relying on Django for the webserver.  If I can serve the whole site (not including the video) statically via IPFS it'd make things a lot simpler and much more difficult to take down.

**Comment by warren-bank** [comment]
Well, I guess I've been tinkering with a lot of decentralized technologies lately. Between IPFS and Ethereum dApps.. my current thinking tends to gravitate toward P2P and blockchain.. and away from centralized servers and traditional backends.

Something like sharing popular videos could live entirely in a front-end (IPFS-enabled) app. The real problem to solve is making content searchable. Think of torrents.. and how all you need is an infoHash (ex: magnet link). Then think of how indexing these infoHashes is the weak point.. sites like piratebay are routinely taken down.. and there's no good search tool. Let alone, a way to identify duplicate files that may exist across different torrents. IPFS indexes file trees the same way that git does.. using a Merkle tree, and allowing each file to be uniquely addressed by its own hash. In this sense, IPFS is a lot like the bittorrent network.. but uses much smarter data structures.

I'm no expert.. but it seems to me that if a video is incredibly popular for a period of time.. rather than having a large number of users slamming a single server (or CDN).. a smarter (and faster and cheaper) methodology to distribute the video data would be P2P.. via content-addressable links.. each user downloading many small chunks of data in parallel from a large number of peers within a swarm. Streaming should just be a matter of configuring how the chunks are prioritized.. and managing a memory buffer rather than writing to disk.

idk.. I haven't given it too much thought. Maybe the answer is a decentralized naming service.. either a smart contract on the Ethereum blockchain.. or using IPFS's own native naming service: IPNS. Then again, maybe not.. but it's fun to think about :)

**Comment by danielquinn** [comment]
All good points, but I'd have to do some experimentation.  The key issue for me is a low barrier for entry, as most Youtubers aren't technical at all and use the platform due to the low cost ($0).

In order for them to move to a federated platform that they'd have to pay for, I want to make sure that the costs are low, which means not saddling a smaller youtuber with a bandwidth bill for a larger one.

Perhaps is IPFS includes some sort of quota system, I could use that, adjusting it based on user preference and/or that user's network usage.

As for search, you're right that's a tough one.  Before I was looking at IPFS I was considering a push notification system that notifies the swarm of new data which is then indexed locally on every instance (using PostgreSQL).  Even 10million records is doable for Postgres for simple search, but I'd also consider ElasticSearch should I be able to keep the resources required low.  That way, all searches are done locally, but will be "eventually consistent" in terms of what's available out there.

Most of my experience is in web development: Python/Django/PostgreSQL so these are the tools I reach for.  My experience with blockchain, DHT in general, and IPFS is close to zero, so this is a learning experience for me wherein I attempt to build something useful.
