### ISSUE TITLE
float values shown as integers

### ISSUE THREAD

**Issue by eadmaster** [warren-bank/moz-json-data-view#16]
when i open a Json like this, floats are shown as integers without the ending ".0":

{
          "timestamp" : "2018-02-01T19:37:51Z",
          "battery_percent" : 99.0,
          "temperature" : 24.0
}

**Comment by warren-bank** [comment]
two thoughts..

1) this addon is deprecated.. since Firefox has moved on and this type of addon can no-longer be installed or used in recent builds

2) numeric values in the JSON data are parsed as numbers.. rather than treated as verbatim strings

```javascript
let x = Number("1.0")
console.log(JSON.stringify(x))
// "1"
```

**Comment by eadmaster** [comment]
I see, so the [problem is related to JS standard JSON serializer](https://stackoverflow.com/questions/41399380/force-float-value-when-using-json-stringify) and cannot be fixes easily...

**Comment by warren-bank** [comment]
the purpose of JSON is to serialize data.. so it can later be parsed by javascript back into a data structure. Since javascript sees the numeric values "1.0" and "1" as being equivalent.. and are represented internally by the same data structure, there's really no reason (or harm) for the JSON to contain unnecessary significant digits. The only reason for wanting such extra data would be user preference. Strictly speaking, such functionally could be baked into a viewer (such as this one).. with special parsing logic. But, at this point, I'm not making any more changes to this add-on. Maybe you'll be able to find a different viewer that supports this "feature". Or, maybe you'll fork this repo and make the necessary changes yourself.. the beauty of open-source. Best of luck.

**Comment by eadmaster** [comment]
I am using this with Palemoon that has limited addon compatibility.
As an easy workaround i'll just switch to the source view (still better than viewing unformatted jsons)

**Comment by warren-bank** [comment]
assuming that the preference to use the alternate JSON parser is active (which it should be).. here are the important lines of code to inspect/modify..

https://github.com/warren-bank/moz-json-data-view/blob/master/chrome/content/JSON-DataView.js#L201
https://github.com/warren-bank/moz-json-data-view/blob/master/chrome/content/jsonTreeViewer.js#L213

https://github.com/sidorares/json-bigint
https://github.com/sidorares/json-bigint/blob/master/lib/parse.js#L64
* `var json_parse = function (options) {...}`

https://github.com/MikeMcl/bignumber.js
https://github.com/MikeMcl/bignumber.js/blob/master/bignumber.js#L2518
* `P.toString = function (b) {...}`

**Comment by warren-bank** [comment]
it may be as simple as passing an option to the parser: `{storeAsString: true}`

..dunno
